const domain = [
  "Please Select",
  "3G/4G Network Evolutions",
  "Action Languages",
  "Agents and Multi-agent Systems",
  "Ambient Assisted Living",
  "Ambient Intelligence",
  "Ant colony optimization",
  "Artificial Consciousness and Artificial Brain",
  "Artificial Imagination",
  "Artificial Intelligence",
  "Artificial Intuition",
  "Artificial Neural Networks",
  "Assistive Robots",
  "Augmented Reality",
  "Automated Planning And Scheduling",
  "Autonomous Robots",
  "Bayesian networks",
  "Big Data",
  "Big data analytics for security",
  "Bioinformatics",
  "Biometrics",
  "Business Intelligence",
  "Cellular Networks",
  "Cloud Computing",
  "Cognitive Radio",
  "Collaborative Learning",
  "Combinatorial optimization",
  "Communication",
  "Communication Protocols",
  "Computational Creativity",
  "Computational Intelligence",
  "Computational Learning Theory",
  "Computer Aided Network Design",
  "Computer Forensics",
  "Computer Networks",
  "Creative and Entertaining Robots",
  "Cryptography",
  "Curriculum Content Design",
  "Cyber Security",
  "Data Mining",
  "Data Retrieval and Data Mining",
  "Data Science",
  "Databases",
  "Decision Making",
  "Decision Support Systems",
  "Decision theory",
  "Delivery Systems and Environments",
  "Design Automation",
  "Digital Circuits",
  "Digital Communication Systems",
  "Digital Goods and Services",
  "Digital Marketing",
  "Digital Signal Processing",
  "Distance Learning",
  "Distributed Computing",
  "Distributed Systems",
  "Dynamic programming",
  "e-Business",
  "e-Commerce",
  "Educational Systems Design",
  "e-Governance",
  "e-Learning",
  "e-Learning Organisational Issues",
  "e-Learning Tools",
  "Electronic Data Interchange (EDI)",
  "Electronics",
  "Enterprise Resource Planning",
  "Evolutionary Algorithms",
  "Evolutionary Computing",
  "E-Waste",
  "Expert Systems",
  "Facial and Object Recognition",
  "Fuzzy Logic",
  "General Intelligence",
  "Genetic Algorithms",
  "Geographic Information Systems",
  "GPS",
  "Green Computing",
  "Health care Systems",
  "High Performance Computing",
  "Human Computer Interaction",
  "Human-Robot Interaction",
  "Image Processing and Analysis",
  "Image/Video Processing",
  "Information Retrieval",
  "Information Theory",
  "Intelligent Driving",
  "Intelligent Systems",
  "Internet of Things",
  "Internet Security",
  "Intrusion Detection",
  "Knowledge Engineering and Mining",
  "Knowledge Management",
  "Knowledge Representation",
  "Localization",
  "Machine Learning",
  "Machine Perception",
  "Machine Vision",
  "Medical Diagnosis",
  "Mobile Adhoc Networks",
  "Mobile Applications",
  "Mobile Communications",
  "Mobile Robots",
  "Motion And Manipulation",
  "Motion Planning",
  "Multimedia Communication",
  "Natural Language Processing",
  "Network Security",
  "Networking",
  "Neural Networks",
  "Neuro-Fuzzy Systems",
  "Numerical Analysis",
  "Ontology Engineering",
  "Open Spectrum Solutions",
  "Optical Communication Systems",
  "Parallel and Distributed Computing",
  "Parallel Computing",
  "Pattern Recognition",
  "Perception and Learning",
  "Pervasive Computing",
  "Planning",
  "Power Electronics",
  "Problem Solving",
  "Quality of Service",
  "Quantum Computing",
  "Robotics",
  "Satellite Communication Systems",
  "SCADA",
  "Secure Protocols",
  "Secure Transactions",
  "Security",
  "Security Intelligence",
  "Segmentation Techniques",
  "Semantic Networks",
  "Sensing and Sensor Networks",
  "Sentiment Analysis",
  "Signal Processing",
  "Simulation",
  "Smart Buildings and Cities",
  "Smart Cities",
  "Smart Grid",
  "Smart Healthcare",
  "Social Computing",
  "Soft Computing",
  "Software Engineering",
  "Software Quality",
  "Spam Detection",
  "Speech Recognition",
  "Supervised and Unsupervised Learning",
  "Support Vector Machines",
  "Swarm Intelligence",
  "Systems Architectures",
  "Technology Trends",
  "Unmanned Systems",
  "Video Analysis",
  "Virtual Learning Environments",
  "Virtual Reality",
  "Web Analytics",
  "Web Services and Performance",
  "Web-based Learning Communities",
  "Wireless Communication",
];

export default domain;
