export const keywordsFilter = [
  { value: "abstract", label: "Abstract" },
  { value: "analysis", label: "Analysis" },
  { value: "artificial_intelligence", label: "Artificial Intelligence" },
  { value: "assessment", label: "Assessment" },
  { value: "behavior", label: "Behavior" },
  { value: "biodiversity", label: "Biodiversity" },
  { value: "biology", label: "Biology" },
  { value: "biotechnology", label: "Biotechnology" },
  { value: "business", label: "Business" },
  { value: "cancer", label: "Cancer" },
  { value: "case_study", label: "Case Study" },
  { value: "chemistry", label: "Chemistry" },
  { value: "climate_change", label: "Climate Change" },
  { value: "cognitive_science", label: "Cognitive Science" },
  { value: "collaboration", label: "Collaboration" },
  { value: "community", label: "Community" },
  { value: "comparative_study", label: "Comparative Study" },
  { value: "computer_science", label: "Computer Science" },
  { value: "conservation", label: "Conservation" },
  { value: "culture", label: "Culture" },
  { value: "data", label: "Data" },
  { value: "data_analysis", label: "Data Analysis" },
  { value: "decision_making", label: "Decision Making" },
  { value: "development", label: "Development" },
  { value: "disease", label: "Disease" },
  { value: "diversity", label: "Diversity" },
  { value: "dna", label: "DNA" },
  { value: "ecology", label: "Ecology" },
  { value: "economics", label: "Economics" },
  { value: "education", label: "Education" },
  { value: "efficacy", label: "Efficacy" },
  { value: "engineering", label: "Engineering" },
  { value: "environment", label: "Environment" },
  { value: "environmental_science", label: "Environmental Science" },
  { value: "ethics", label: "Ethics" },
  { value: "evaluation", label: "Evaluation" },
  { value: "evolution", label: "Evolution" },
  { value: "experiment", label: "Experiment" },
  { value: "exploration", label: "Exploration" },
  { value: "finance", label: "Finance" },
  { value: "forecasting", label: "Forecasting" },
  { value: "genetics", label: "Genetics" },
  { value: "geography", label: "Geography" },
  { value: "geology", label: "Geology" },
  { value: "global", label: "Global" },
  { value: "health", label: "Health" },
  { value: "healthcare", label: "Healthcare" },
  { value: "history", label: "History" },
  { value: "human_resources", label: "Human Resources" },
  { value: "impact", label: "Impact" },
  { value: "implementation", label: "Implementation" },
  { value: "innovation", label: "Innovation" },
  { value: "internet", label: "Internet" },
  { value: "investigation", label: "Investigation" },
  { value: "leadership", label: "Leadership" },
  { value: "learning", label: "Learning" },
  { value: "literature", label: "Literature" },
  { value: "machine_learning", label: "Machine Learning" },
  { value: "management", label: "Management" },
  { value: "marketing", label: "Marketing" },
  { value: "medicine", label: "Medicine" },
  { value: "methodology", label: "Methodology" },
  { value: "microbiology", label: "Microbiology" },
  { value: "modeling", label: "Modeling" },
  { value: "molecular_biology", label: "Molecular Biology" },
  { value: "nanotechnology", label: "Nanotechnology" },
  { value: "network", label: "Network" },
  { value: "neuroscience", label: "Neuroscience" },
  { value: "nutrition", label: "Nutrition" },
  { value: "observation", label: "Observation" },
  { value: "organizational_behavior", label: "Organizational Behavior" },
  { value: "pathology", label: "Pathology" },
  { value: "patient_care", label: "Patient Care" },
  { value: "performance", label: "Performance" },
  { value: "pharmaceuticals", label: "Pharmaceuticals" },
  { value: "physics", label: "Physics" },
  { value: "policy", label: "Policy" },
  { value: "political_science", label: "Political Science" },
  { value: "population", label: "Population" },
  { value: "prediction", label: "Prediction" },
  { value: "productivity", label: "Productivity" },
  { value: "psychology", label: "Psychology" },
  { value: "public_health", label: "Public Health" },
  { value: "quality", label: "Quality" },
  { value: "quantitative", label: "Quantitative" },
  { value: "radiology", label: "Radiology" },
  { value: "rehabilitation", label: "Rehabilitation" },
  { value: "renewable_energy", label: "Renewable Energy" },
  { value: "research", label: "Research" },
  { value: "review", label: "Review" },
  { value: "risk", label: "Risk" },
  { value: "safety", label: "Safety" },
  { value: "science", label: "Science" },
  { value: "simulation", label: "Simulation" },
  { value: "social_media", label: "Social Media" },
  { value: "social_science", label: "Social Science" },
  { value: "sociology", label: "Sociology" },
  { value: "software", label: "Software" },
  { value: "statistics", label: "Statistics" },
  { value: "sustainability", label: "Sustainability" },
  { value: "technology", label: "Technology" },
  { value: "therapy", label: "Therapy" },
  { value: "toxicology", label: "Toxicology" },
  { value: "training", label: "Training" },
  { value: "transportation", label: "Transportation" },
  { value: "treatment", label: "Treatment" },
  { value: "trends", label: "Trends" },
  { value: "urban_planning", label: "Urban Planning" },
  { value: "validation", label: "Validation" },
  { value: "value", label: "Value" },
  { value: "variance", label: "Variance" },
  { value: "veterinary", label: "Veterinary" },
  { value: "virology", label: "Virology" },
  { value: "water", label: "Water" },
  { value: "wellness", label: "Wellness" },
  { value: "youth", label: "Youth" },
  { value: "algorithm", label: "Algorithm" },
  { value: "anthropology", label: "Anthropology" },
  { value: "aptitude", label: "Aptitude" },
  { value: "biomarkers", label: "Biomarkers" },
  { value: "brain", label: "Brain" },
  { value: "cell", label: "Cell" },
  { value: "climate", label: "Climate" },
  { value: "compounds", label: "Compounds" },
  { value: "cryptography", label: "Cryptography" },
  { value: "cybersecurity", label: "Cybersecurity" },
  { value: "design", label: "Design" },
  { value: "diagnostics", label: "Diagnostics" },
  { value: "diffusion", label: "Diffusion" },
  { value: "dynamics", label: "Dynamics" },
  { value: "econometrics", label: "Econometrics" },
  { value: "ecosystem", label: "Ecosystem" },
  { value: "efficiency", label: "Efficiency" },
  { value: "endocrinology", label: "Endocrinology" },
  { value: "energy", label: "Energy" },
  { value: "entropy", label: "Entropy" },
  { value: "epigenetics", label: "Epigenetics" },
  { value: "epidemiology", label: "Epidemiology" },
  { value: "epistemology", label: "Epistemology" },
  { value: "equity", label: "Equity" },
  { value: "ethnography", label: "Ethnography" },
  { value: "evolutionary_biology", label: "Evolutionary Biology" },
  { value: "finite_element_analysis", label: "Finite Element Analysis" },
  { value: "forensics", label: "Forensics" },
  { value: "genomics", label: "Genomics" },
  { value: "geophysics", label: "Geophysics" },
  { value: "governance", label: "Governance" },
  { value: "growth", label: "Growth" },
  { value: "heuristics", label: "Heuristics" },
  { value: "hydrology", label: "Hydrology" },
  { value: "informatics", label: "Informatics" },
  { value: "innovation_management", label: "Innovation Management" },
  { value: "integration", label: "Integration" },
  { value: "internet_of_things", label: "Internet of Things" },
  { value: "kinetics", label: "Kinetics" },
  { value: "linguistics", label: "Linguistics" },
  { value: "logistics", label: "Logistics" },
  { value: "magnetism", label: "Magnetism" },
  { value: "mathematics", label: "Mathematics" },
  { value: "mechanics", label: "Mechanics" },
  { value: "metabolism", label: "Metabolism" },
  { value: "microeconomics", label: "Microeconomics" },
  { value: "migration", label: "Migration" },
  { value: "morphology", label: "Morphology" },
  { value: "neurobiology", label: "Neurobiology" },
  { value: "nursing", label: "Nursing" },
  { value: "optimization", label: "Optimization" },
  { value: "paleontology", label: "Paleontology" },
  { value: "pathogenesis", label: "Pathogenesis" },
  { value: "photonics", label: "Photonics" },
  { value: "physiology", label: "Physiology" },
  { value: "planetary_science", label: "Planetary Science" },
  { value: "plasma", label: "Plasma" },
  { value: "proteomics", label: "Proteomics" },
  { value: "psychiatry", label: "Psychiatry" },
  { value: "public_policy", label: "Public Policy" },
  { value: "quantum_mechanics", label: "Quantum Mechanics" },
  { value: "recombination", label: "Recombination" },
  { value: "regeneration", label: "Regeneration" },
  { value: "regulation", label: "Regulation" },
  { value: "remote_sensing", label: "Remote Sensing" },
  { value: "resource_management", label: "Resource Management" },
  { value: "robotics", label: "Robotics" },
  { value: "semiotics", label: "Semiotics" },
  { value: "seismology", label: "Seismology" },
  { value: "signal_processing", label: "Signal Processing" },
  { value: "soil_science", label: "Soil Science" },
  { value: "spectroscopy", label: "Spectroscopy" },
  { value: "supply_chain", label: "Supply Chain" },
  { value: "surgery", label: "Surgery" },
  { value: "sustainable_development", label: "Sustainable Development" },
  { value: "systems_biology", label: "Systems Biology" },
  { value: "telecommunications", label: "Telecommunications" },
  { value: "thermodynamics", label: "Thermodynamics" },
  { value: "tissue_engineering", label: "Tissue Engineering" },
  { value: "toxicity", label: "Toxicity" },
  { value: "trade", label: "Trade" },
  { value: "transcription", label: "Transcription" },
  { value: "urbanization", label: "Urbanization" },
  { value: "usability", label: "Usability" },
  { value: "viability", label: "Viability" },
  { value: "visualization", label: "Visualization" },
  { value: "waste_management", label: "Waste Management" },
  { value: "web_development", label: "Web Development" },
  { value: "zoology", label: "Zoology" },
];
